services:
  caddy:
    image: caddy:latest
    container_name: caddy_public
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
    volumes:
    - ~/webpages:/webpages
    - ${PWD}/data:/data
    - ${PWD}/config:/config
    - ${PWD}/caddyfile:/etc/caddy
    networks:
    - default
    - supabase_default  # This connects to Supabase network

# Define the external network (created by your Supabase setup)
networks:
  supabase_default:
    external: true
